### ISSUE TITLE
Choose a good name for the project

### ISSUE THREAD

**Issue by aboucaud** [DifferentiableUniverseInitiative/sbi_lens#14]
There are few kinds of GitHub projects. The ones that aim at being imported as a library in other codes (numpy, tensorflow, jax) and the standalone ones that have a single purpose (produce data, reproduce an analysis, run a benchmark).
Depending on the category, the name of the project is more or less important.

Then there are a few considerations, Python-wise
- short names should be preferred
- a non existing package on [pypi](https://pypi.org/)

You can also have a project name that is different from the Python package name (e.g. "scikit-learn" vs. `sklearn`)

In your case, you might want the name to convey the purpose of the package, or give it the name of your choosing. 
But at least we should start discussing it here.

**Comment by dlanzieri** [comment]
I vote for a name that conveys the purpose of the package!
If we decided on this option, maybe we could start thinking of a few keywords and then see if we can find a name or nice acronyms that convey/incorporate these words. 
I would say, for example:

1. Differentiable simulator
2. Implicit likelihood
3. Weak lensing (even though the simulator could generate also density maps one day, so I don't know if we want to specify it )
Other ideas?

**Comment by Justinezgh** [comment]
Can we put 'ax' at the end ? :D
