### ISSUE TITLE
Add pre sampled reference posteriors 

### ISSUE THREAD

**Issue by Justinezgh** [DifferentiableUniverseInitiative/sbi_lens#16]
@dlanzieri we have functions to compute reference posteriors but running mcmcs can be very long. Do we want to pre run mcmcs and save the chains in the data folder for specific cases like the one corresponding to lsst year 1 or year 10 for instance? It can be accessed through the functions if we use the following names: 

```python 
"posterior_power_spectrum__{}N_{}ms_{}gpa_{}se.npy".format(N, map_size, gals_per_arcmin2, sigma_e)
"posterior_power_spectrum__{}N_{}ms_{}gpa_{}se.npy".format(N, map_size, gals_per_arcmin2, sigma_e)
"m_data__{}N_{}ms_{}gpa_{}se.npy".format(N, map_size, gals_per_arcmin2, sigma_e)
```

**Comment by dlanzieri** [comment]
@Justinezgh I think it would be very useful, but maybe not now.  We are using only a toy model for the simulator, to produce scientific results we want to refine the simulator (for example using the correct shift parameters).
