### ISSUE TITLE
Package Structure

### ISSUE THREAD

**Issue by dlanzieri** [DifferentiableUniverseInitiative/sbi_lens#2]
Hello @EiffL @Justinezgh @aboucaud  ! This first issue is to keep track of development needed to build the SBI package.
In this [PR](https://github.com/DifferentiableUniverseInitiative/sbi_lens/pull/1), we can find the first prototype for the general structure. There's a lot more to do!

## Task

- [x] #14
- [x] Track/Update the [requirements.txt](https://github.com/DifferentiableUniverseInitiative/sbi_lens/blob/dlanzieri/file_structure/requirements.txt)
- [x] Track/Update the [setup.py](https://github.com/DifferentiableUniverseInitiative/sbi_lens/blob/dlanzieri/file_structure/setup.py)
- [x] #12
- [x] #13

If you think something else we should do, please add a TODO list in this issue! :-)

**Comment by aboucaud** [comment]
[ ] Add pre-commit config
