### ISSUE TITLE
LSST year 10 setting

### ISSUE THREAD

**Issue by Justinezgh** [DifferentiableUniverseInitiative/sbi_lens#29]
**Redshift**
- 5 redshift bins 
- equal number of galaxies 
- redshift distribution: 
    <img width="239" alt="image" src="https://user-images.githubusercontent.com/72011736/230109557-58bdab56-4beb-4f63-98bb-25b4f93a088c.png">
    with (alpha, z0) = (0.11, 0.68)

**Number density**

- 27 / arcmin^2

**Shape Noise** 

- 0.27

**Map size**

- 10 degree 

**Number of pixels**

- 256

**Comment by dlanzieri** [comment]
@Justinezgh Since all of those are part of our last PR, I'll close this issue!
