### ISSUE TITLE
Starting adding features 

### ISSUE THREAD

**Issue by dlanzieri** [DifferentiableUniverseInitiative/sbi_lens#3]
Hello @Justinezgh !
We can finally start adding pieces of code to the repo. 
As discussed, we should work making our own branch and adding features via PR. 
As a good starting point we could add:

- [x] The python scripts defining the physical models of the simulator (e.g [simulator](https://github.com/DifferentiableUniverseInitiative/sbi_lens/tree/dlanzieri/file_structure/sbi_lens/simulator))
- [x] All the python scripts required to generate/load the dataset (e.g [gen_dataset](https://github.com/DifferentiableUniverseInitiative/sbi_lens/tree/dlanzieri/file_structure/sbi_lens/gen_dataset) )
- [x] The codes defining the NF used (e.g [normflow](https://github.com/DifferentiableUniverseInitiative/sbi_lens/tree/dlanzieri/file_structure/sbi_lens/normflow))
- [x] All the mathematical functions needed to other tasks (e.g [bijectors](https://github.com/DifferentiableUniverseInitiative/sbi_lens/tree/dlanzieri/file_structure/sbi_lens/bijectors) )

We should also make sure we  always document the Python codes! :)

**Comment by EiffL** [comment]
This is a good decomposition of tasks I think :-) Let's get started:

@dlanzieri can you add the code for the physical model? (point 1)

@Justinezgh can you add the code for generating datasets from this physical model? (point 2)

You can turn each of these bullet points into issues, and assign yourselves to them.

**Comment by aboucaud** [comment]
Shall we close this issue ?

**Comment by dlanzieri** [comment]
yes, I guess we can since we completed all the tasks :-)
